server:
  port: 8083

spring:
  application:
    name: Energy-Meter-Notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: my-consumer-group
    value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

variable:
  high-consumption: 20000
  moderate-consumption: 10000
  low-consumption: 18000
  excessive-consumption: 30000
